import Nav from "./Nav";
import { useRouter } from "next/router";
import Head from "next/head";

const MainLayout = ({ children, title = "empty title" }) => {
  const { pathname: path } = useRouter();

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="keywords" content="next,js,react" />
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
      </Head>

      {/*<Nav activePath={path} />*/}

      <main>{children}</main>
    </>
  );
};

export default MainLayout;
